#!/bin/sh
# Point the official Codex CLI at a CoCodex subscription gateway.
#
# The gateway serves this file with its own URL baked in, so the usual way to
# run it is:
#
#   curl -fsSL https://<gateway>/install.sh | sh
#
# From a checkout the gateway URL is the first argument instead:
#
#   ./scripts/install.sh http://127.0.0.1:53141
#
# It writes ~/.codex/config.toml (openai_base_url / chatgpt_base_url) and an
# env file for the login issuer and refresh/revoke overrides, then hooks that
# env file into the rc file of your login shell. Codex does not read those
# OAuth URLs from config.toml, so environment variables are the only way in.
#
# Desktop apps do not read shell rc files, so the same variables are also
# published to the GUI session: a LaunchAgent running `launchctl setenv` on
# macOS, ~/.config/environment.d on Linux. With CODEX_APP_SERVER_LOGIN_ISSUER
# set, "Sign in with ChatGPT" in the Codex desktop app (and IDE extensions)
# logs in against the gateway through the browser, no device code needed.
set -eu

# Replaced by the gateway when it serves this script over HTTP; empty here.
GATEWAY_DEFAULT=""

BEGIN="# >>> cocodex-gateway >>>"
END="# <<< cocodex-gateway <<<"

usage() {
  cat <<'EOF'
Usage: install.sh [gateway-url] [--login | --no-login]

  gateway-url   CoCodex gateway origin, e.g. http://127.0.0.1:53141
                Optional when the script was downloaded from a gateway.
  --login       Run Codex device-code login after writing the config
  --no-login    Never log in, just write the config

Without either flag the login runs only when codex is on PATH and a
terminal is attached.

This updates:
  ~/.codex/config.toml
  ~/.codex/cocodex-gateway.env
  your shell rc (zsh/bash/fish/profile)
  macOS: ~/Library/LaunchAgents/app.cocodex.gateway-env.plist
  Linux: ~/.config/environment.d/cocodex-gateway.conf
EOF
}

warn() {
  printf 'WARNING: %s\n' "$1" >&2
}

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

# A terminal we can actually read from: the device node can exist and still
# refuse to open when the process has no controlling terminal.
has_tty() {
  # In a subshell: a failed redirection on a special built-in such as `:`
  # would otherwise end the whole script under a POSIX shell.
  ( : </dev/tty ) 2>/dev/null
}

# macOS has no GNU mktemp: a template argument is required there.
make_temp() {
  mktemp "${TMPDIR:-/tmp}/cocodex-install.XXXXXX"
}

GATEWAY="$GATEWAY_DEFAULT"
DO_LOGIN=auto

for arg in "$@"; do
  case "$arg" in
    --login) DO_LOGIN=1 ;;
    --no-login) DO_LOGIN=0 ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      printf 'Unknown option: %s\n' "$arg" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [ -n "$GATEWAY" ] && [ "$GATEWAY" != "$GATEWAY_DEFAULT" ]; then
        printf 'Unexpected extra argument: %s\n' "$arg" >&2
        usage >&2
        exit 2
      fi
      GATEWAY=$arg
      ;;
  esac
done

if [ -z "$GATEWAY" ]; then
  usage >&2
  exit 2
fi

case "$GATEWAY" in
  http://*|https://*) ;;
  *) die "gateway-url must start with http:// or https://" ;;
esac

GATEWAY=$(printf '%s' "$GATEWAY" | sed 's|/*$||')
OPENAI_BASE_URL="${GATEWAY}/backend-api/codex"
CHATGPT_BASE_URL="${GATEWAY}/backend-api"
REFRESH_URL="${GATEWAY}/oauth/token"
REVOKE_URL="${GATEWAY}/oauth/revoke"
# Codex appends /oauth/authorize, /oauth/token and the device-code paths.
LOGIN_ISSUER="$GATEWAY"

case "$(uname -s 2>/dev/null || echo unknown)" in
  Darwin) OS=darwin ;;
  Linux) OS=linux ;;
  MINGW*|MSYS*|CYGWIN*)
    die "On Windows run install.ps1 instead: irm ${GATEWAY}/install.ps1 | iex"
    ;;
  *)
    OS=other
    warn "Unrecognized OS $(uname -s 2>/dev/null || echo unknown); continuing as a generic POSIX system."
    ;;
esac

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
TOML="$CODEX_HOME/config.toml"
ENV_FILE="$CODEX_HOME/cocodex-gateway.env"

mkdir -p "$CODEX_HOME"

# The rc block refers to the env file through $HOME when it lives there, so a
# synced dotfile keeps working under a different user.
env_file_expr() {
  case "$ENV_FILE" in
    "$HOME"/*) printf '"$HOME/%s"' "${ENV_FILE#"$HOME"/}" ;;
    *) printf '"%s"' "$ENV_FILE" ;;
  esac
}

upsert_toml() {
  tmp=$(make_temp)
  {
    printf 'openai_base_url = "%s"\n' "$OPENAI_BASE_URL"
    printf 'chatgpt_base_url = "%s"\n' "$CHATGPT_BASE_URL"
    printf '\n'
    if [ -f "$TOML" ]; then
      # Drop the keys we are about to write, then the blank lines they left
      # behind, so repeated runs do not grow the file.
      grep -v -E '^[[:space:]]*openai_base_url[[:space:]]*=' "$TOML" \
        | grep -v -E '^[[:space:]]*chatgpt_base_url[[:space:]]*=' \
        | awk 'NF { seen = 1 } seen { print }' || true
    fi
  } >"$tmp"
  cat "$tmp" >"$TOML"
  rm -f "$tmp"
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by the CoCodex install script. Sourced from your shell rc.
export CODEX_APP_SERVER_LOGIN_ISSUER="${LOGIN_ISSUER}"
export CODEX_REFRESH_TOKEN_URL_OVERRIDE="${REFRESH_URL}"
export CODEX_REVOKE_TOKEN_URL_OVERRIDE="${REVOKE_URL}"
EOF
}

# Login shell, from $SHELL when the terminal exported one, otherwise from the
# account database: `curl | sh` runs under /bin/sh, so $0 says nothing useful.
detect_shell() {
  name=""
  if [ -n "${SHELL:-}" ]; then
    name=$(basename "$SHELL")
  fi
  if [ -z "$name" ] || [ "$name" = "sh" ]; then
    entry=""
    if command -v getent >/dev/null 2>&1; then
      entry=$(getent passwd "$(id -u)" 2>/dev/null | awk -F: 'NR==1 {print $7}')
    elif [ "$OS" = darwin ]; then
      entry=$(dscl . -read "/Users/$(id -un)" UserShell 2>/dev/null | awk 'NR==1 {print $2}')
    fi
    if [ -n "$entry" ]; then
      name=$(basename "$entry")
    fi
  fi
  printf '%s\n' "${name:-sh}"
}

# bash reads ~/.bashrc for interactive shells, but macOS terminals start login
# shells, which read only the first of .bash_profile/.bash_login/.profile that
# exists. Creating .bash_profile when one of the others is already there would
# shadow it, so reuse whichever the account already has.
bash_login_rc() {
  for candidate in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
    if [ -f "$candidate" ]; then
      printf '%s\n' "$candidate"
      return
    fi
  done
  printf '%s\n' "$HOME/.bash_profile"
}

# Every rc file that should source the env file, one per line.
rc_targets() {
  case "$(detect_shell)" in
    zsh)
      printf '%s\n' "posix ${ZDOTDIR:-$HOME}/.zshrc"
      ;;
    bash)
      printf '%s\n' "posix $HOME/.bashrc"
      if [ "$OS" = darwin ]; then
        printf '%s\n' "posix $(bash_login_rc)"
      fi
      ;;
    fish)
      printf '%s\n' "fish ${XDG_CONFIG_HOME:-$HOME/.config}/fish/config.fish"
      ;;
    ksh|mksh|ksh93)
      printf '%s\n' "posix $HOME/.profile"
      printf '%s\n' "posix $HOME/.kshrc"
      ;;
    *)
      printf '%s\n' "posix $HOME/.profile"
      ;;
  esac
}

strip_rc_block() {
  rc=$1
  [ -f "$rc" ] || return 0
  tmp=$(make_temp)
  awk -v begin="$BEGIN" -v end="$END" '
    $0 == begin { skip=1; next }
    $0 == end { skip=0; next }
    skip != 1 { print }
  ' "$rc" >"$tmp"
  # Copy rather than move so the rc file keeps its mode and any symlink.
  cat "$tmp" >"$rc"
  rm -f "$tmp"
}

install_hook() {
  kind=$1
  rc=$2
  mkdir -p "$(dirname "$rc")"
  [ -f "$rc" ] || : >"$rc"
  strip_rc_block "$rc"
  if [ "$kind" = fish ]; then
    cat >>"$rc" <<EOF
$BEGIN
# Managed by the CoCodex install script. Delete this block to undo.
set -gx CODEX_APP_SERVER_LOGIN_ISSUER "${LOGIN_ISSUER}"
set -gx CODEX_REFRESH_TOKEN_URL_OVERRIDE "${REFRESH_URL}"
set -gx CODEX_REVOKE_TOKEN_URL_OVERRIDE "${REVOKE_URL}"
$END
EOF
  else
    cat >>"$rc" <<EOF
$BEGIN
# Managed by the CoCodex install script. Delete this block to undo.
if [ -f $(env_file_expr) ]; then
  . $(env_file_expr)
fi
$END
EOF
  fi
}

# The variables a GUI-launched Codex needs, one "NAME VALUE" per line.
gui_env() {
  printf '%s %s\n' \
    CODEX_APP_SERVER_LOGIN_ISSUER "$LOGIN_ISSUER" \
    CODEX_REFRESH_TOKEN_URL_OVERRIDE "$REFRESH_URL" \
    CODEX_REVOKE_TOKEN_URL_OVERRIDE "$REVOKE_URL"
}

# macOS apps started from Finder or the Dock inherit launchd's environment.
# `launchctl setenv` covers apps opened from now on; the LaunchAgent repeats
# it at every login, since launchd forgets it on reboot.
install_macos_gui_env() {
  agents="$HOME/Library/LaunchAgents"
  plist="$agents/app.cocodex.gateway-env.plist"
  commands=""
  while IFS=' ' read -r name value; do
    launchctl setenv "$name" "$value" 2>/dev/null \
      || warn "launchctl setenv $name failed; the desktop app will see it after your next login."
    commands="${commands}/bin/launchctl setenv $name '$value'; "
  done <<EOF
$(gui_env)
EOF
  mkdir -p "$agents"
  cat >"$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by the CoCodex install script. Delete this file to undo. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>app.cocodex.gateway-env</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>${commands}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF
  GUI_ENV_FILE=$plist
}

# systemd user sessions (GNOME, KDE, ...) load environment.d at login, which
# reaches editors and apps started from the desktop rather than a terminal.
install_linux_gui_env() {
  dir="${XDG_CONFIG_HOME:-$HOME/.config}/environment.d"
  conf="$dir/cocodex-gateway.conf"
  mkdir -p "$dir"
  {
    echo "# Generated by the CoCodex install script. Delete this file to undo."
    gui_env | while IFS=' ' read -r name value; do
      printf '%s=%s\n' "$name" "$value"
    done
  } >"$conf"
  GUI_ENV_FILE=$conf
}

upsert_toml
write_env_file
GUI_ENV_FILE=""
case "$OS" in
  darwin) install_macos_gui_env ;;
  linux) install_linux_gui_env ;;
esac

# `rc_targets` prints "kind path"; paths under $HOME never contain newlines.
rc_targets | while IFS=' ' read -r kind rc; do
  [ -n "$rc" ] || continue
  install_hook "$kind" "$rc"
done
RC_FILES=$(rc_targets | cut -d' ' -f2-)

# Make the overrides visible to this process, and so to --login below.
# shellcheck disable=SC1090
. "$ENV_FILE"

echo "Wrote $TOML"
echo "  openai_base_url  = $OPENAI_BASE_URL"
echo "  chatgpt_base_url = $CHATGPT_BASE_URL"
echo "Wrote $ENV_FILE"
printf '%s\n' "$RC_FILES" | while read -r rc; do
  [ -n "$rc" ] || continue
  echo "Hooked $rc"
done
if [ -n "$GUI_ENV_FILE" ]; then
  echo "Wrote $GUI_ENV_FILE"
fi
echo "Open a new terminal, or run: . \"$ENV_FILE\""
echo
echo "Codex desktop app / IDE extension:"
case "$OS" in
  darwin) echo "  quit it completely (Cmd+Q), reopen it, then click \"Sign in with ChatGPT\"." ;;
  *) echo "  log out and back in (or start it from a new terminal), then click \"Sign in with ChatGPT\"." ;;
esac
echo
echo "Codex CLI login (the CLI's browser login ignores a custom issuer):"
echo "  codex login --device-auth --experimental_issuer $GATEWAY"

if [ "$DO_LOGIN" = 0 ]; then
  exit 0
fi

if ! command -v codex >/dev/null 2>&1; then
  if [ "$DO_LOGIN" = 1 ]; then
    die "codex is not on PATH; skip --login"
  fi
  echo
  warn "codex is not on PATH yet. Install it, then run the login command above."
  exit 0
fi

# Under `curl | sh` stdin is the script itself, so the device-code prompt has
# to read from the terminal.
if has_tty; then
  echo
  exec codex login --device-auth --experimental_issuer "$GATEWAY" </dev/tty
fi

if [ "$DO_LOGIN" = 1 ]; then
  echo
  exec codex login --device-auth --experimental_issuer "$GATEWAY"
fi

echo
echo "No terminal attached; run the login command above when you have one."
