#!/bin/sh
# Configure the official Codex CLI to use a CoCodex subscription gateway.
#
# Writes ~/.codex/config.toml (openai_base_url / chatgpt_base_url) and a
# sourced env file for refresh/revoke overrides. Codex does not read those
# OAuth URLs from config.toml.
set -eu

usage() {
  cat <<'EOF'
Usage: install-codex-gateway.sh <gateway-url> [--login]

  gateway-url   CoCodex gateway origin, e.g. http://127.0.0.1:53141
  --login       After writing config, run Codex device-code login

This updates:
  ~/.codex/config.toml
  ~/.codex/cocodex-gateway.env
  your shell rc (zsh/bash/fish/profile)

Codex cannot persist CODEX_REFRESH_TOKEN_URL_OVERRIDE in config.toml;
the env file + rc hook is the supported workaround.
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

GATEWAY=""
DO_LOGIN=0
for arg in "$@"; do
  case "$arg" in
    --login) DO_LOGIN=1 ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [ -n "$GATEWAY" ]; then
        echo "Unexpected extra argument: $arg" >&2
        usage >&2
        exit 2
      fi
      GATEWAY=$arg
      ;;
  esac
done

if [ -z "$GATEWAY" ]; then
  usage >&2
  exit 2
fi

case "$GATEWAY" in
  http://*|https://*) ;;
  *)
    echo "gateway-url must start with http:// or https://" >&2
    exit 2
    ;;
esac

GATEWAY=$(printf '%s' "$GATEWAY" | sed 's|/*$||')
OPENAI_BASE_URL="${GATEWAY}/backend-api/codex"
CHATGPT_BASE_URL="${GATEWAY}/backend-api"
REFRESH_URL="${GATEWAY}/oauth/token"
REVOKE_URL="${GATEWAY}/oauth/revoke"

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
TOML="$CODEX_HOME/config.toml"
ENV_FILE="$CODEX_HOME/cocodex-gateway.env"
BEGIN="# >>> cocodex-gateway >>>"
END="# <<< cocodex-gateway <<<"

mkdir -p "$CODEX_HOME"

upsert_toml() {
  tmp=$(mktemp)
  {
    printf 'openai_base_url = "%s"\n' "$OPENAI_BASE_URL"
    printf 'chatgpt_base_url = "%s"\n' "$CHATGPT_BASE_URL"
    printf '\n'
    if [ -f "$TOML" ]; then
      grep -v -E '^openai_base_url[[:space:]]*=' "$TOML" \
        | grep -v -E '^chatgpt_base_url[[:space:]]*='
    fi
  } >"$tmp"
  mv "$tmp" "$TOML"
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by install-codex-gateway.sh. Sourced from your shell rc.
export CODEX_REFRESH_TOKEN_URL_OVERRIDE="${REFRESH_URL}"
export CODEX_REVOKE_TOKEN_URL_OVERRIDE="${REVOKE_URL}"
EOF
}

strip_rc_block() {
  rc=$1
  [ -f "$rc" ] || return 0
  tmp=$(mktemp)
  awk -v begin="$BEGIN" -v end="$END" '
    $0 == begin { skip=1; next }
    $0 == end { skip=0; next }
    skip != 1 { print }
  ' "$rc" >"$tmp"
  mv "$tmp" "$rc"
}

detect_rc() {
  shell_name=$(basename "${SHELL:-sh}")
  case "$shell_name" in
    zsh) printf '%s\n' "$HOME/.zshrc" posix ;;
    bash)
      if [ -f "$HOME/.bashrc" ]; then
        printf '%s\n' "$HOME/.bashrc" posix
      else
        printf '%s\n' "$HOME/.bash_profile" posix
      fi
      ;;
    fish) printf '%s\n' "$HOME/.config/fish/config.fish" fish ;;
    *) printf '%s\n' "$HOME/.profile" posix ;;
  esac
}

install_posix_hook() {
  rc=$1
  touch "$rc"
  strip_rc_block "$rc"
  cat >>"$rc" <<EOF
$BEGIN
# Managed by install-codex-gateway.sh
if [ -f "\$HOME/.codex/cocodex-gateway.env" ]; then
  . "\$HOME/.codex/cocodex-gateway.env"
fi
$END
EOF
}

install_fish_hook() {
  rc=$1
  mkdir -p "$(dirname "$rc")"
  touch "$rc"
  strip_rc_block "$rc"
  cat >>"$rc" <<EOF
$BEGIN
# Managed by install-codex-gateway.sh
set -gx CODEX_REFRESH_TOKEN_URL_OVERRIDE "${REFRESH_URL}"
set -gx CODEX_REVOKE_TOKEN_URL_OVERRIDE "${REVOKE_URL}"
$END
EOF
}

upsert_toml
write_env_file

# shellcheck disable=SC2046
set -- $(detect_rc)
RC_FILE=$1
RC_KIND=$2

if [ "$RC_KIND" = "fish" ]; then
  install_fish_hook "$RC_FILE"
else
  install_posix_hook "$RC_FILE"
fi

# Current process (and --login) should see the overrides immediately.
# shellcheck disable=SC1090
. "$ENV_FILE"

echo "Wrote $TOML"
echo "  openai_base_url  = $OPENAI_BASE_URL"
echo "  chatgpt_base_url = $CHATGPT_BASE_URL"
echo "Wrote $ENV_FILE"
echo "Hooked $RC_FILE (open a new terminal, or: . \"$ENV_FILE\")"
echo
echo "Login with:"
echo "  codex login --device-auth --experimental_issuer $GATEWAY"

if [ "$DO_LOGIN" -eq 1 ]; then
  if ! command -v codex >/dev/null 2>&1; then
    echo "codex is not on PATH; skip --login" >&2
    exit 1
  fi
  exec codex login --device-auth --experimental_issuer "$GATEWAY"
fi
